// COLD DEEP LINKS ONTO LAZY DESTINATIONS.
//
// index.html's inline boot script preloads the lazy bundle(s) a deep link needs (and
// starts that route's always-asked reads) while the eager set is still on the wire.
// Its route table is generated by the build from the route grammar, BUNDLES' `views`
// and the loader's own url/dependency tables (scripts/lazy-route-preload.mjs). What
// can go wrong: the committed shell drifts from the build, a view is declared under
// the wrong bundle, a preload url misses the one ensureBundle injects (a double
// download), or an early read is never taken (a wasted request).
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import vm from "node:vm";
import { BUNDLES } from "../scripts/build-client.mjs";
import {
  LAZY_ROUTES_MARKER,
  SHELL_EARLY_READS,
  VIEW_EARLY_READS,
  bundleDigits,
  lazyRoutePreloadTable,
  viewBundleIndex,
  withLazyRouteTable,
} from "../scripts/lazy-route-preload.mjs";
import { earlyFetchScript } from "../dist/earlyFetch.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => readFileSync(path.join(root, file), "utf8");
const html = read("public/index.html");
const table = lazyRoutePreloadTable(root, BUNDLES);

function routesApi() {
  const context = { URL, URLSearchParams, window: {}, globalThis: null };
  context.globalThis = context;
  context.window = context;
  vm.runInNewContext(read("public/js/route-state.js"), context);
  return context.CairnRoutes;
}

function canonicalRoutes() {
  const routes = routesApi();
  const defs = routes.routeDefinitions;
  const sections = new Set([
    ...Object.values(defs.sections).flat(),
    "session",
    "fuel",
    "plan",
    "race",
    "changes",
    "health",
    "settings",
  ]);
  const out = [];
  for (const home of defs.homes) {
    for (const section of ["", ...sections]) {
      const url = `/app/${home}${section ? `/${section}` : ""}?id=x`;
      const route = routes.parseRoute(url);
      if (!route.legacy) out.push({ url, route });
    }
  }
  return out;
}

test("the committed shell carries the table the build derives", () => {
  assert.ok(LAZY_ROUTES_MARKER.test(html), "index.html's boot script carries the generated table");
  assert.equal(withLazyRouteTable(html, table), html, "run npm run build and commit public/index.html");
});

test("every lazy bundle's views are exactly the ones render-dispatch loads it for", () => {
  const bundleOf = viewBundleIndex(BUNDLES);
  const dispatch = read("public/js/app-render-dispatch.js");
  const stub = () => undefined;
  let seen = 0;
  for (const { url, route } of canonicalRoutes()) {
    const asked = [];
    const context = {
      headerTitle: { classList: { remove: stub } },
      document: { getElementById: () => null, body: { classList: { remove: stub }, dataset: {} } },
      updateHeaderCondense: stub,
      state: { planSeg: route.tab === "plan" ? route.section : null, planJump: null },
      withBundle: (name) => asked.push(name),
      renderToday: stub,
      renderSession: stub,
      renderFoodJournal: stub,
      renderMeals: stub,
      renderYou: stub,
      window: {},
      globalThis: null,
    };
    context.globalThis = context;
    vm.runInNewContext(dispatch, context);
    context.renderTab(route.tab);
    assert.deepEqual(asked, bundleOf(route) ? [bundleOf(route)] : [], url);
    seen += 1;
  }
  assert.ok(seen > 20, "the route grammar was enumerated");
});

function lazyLoader() {
  const context = { window: {}, globalThis: null };
  context.globalThis = context;
  vm.runInNewContext(read("public/js/app-lazy-bundles.js"), context);
  return context;
}

test("a preload names the exact url ensureBundle injects, and the worker precaches it", () => {
  const { LAZY_BUNDLE_SRC } = lazyLoader();
  assert.deepEqual([...table.b].sort(), Object.values(LAZY_BUNDLE_SRC).sort());
  const sw = read("public/sw.js");
  for (const url of table.b) {
    assert.ok(!url.includes("?"), `${url} carries no query (it must hit the precache entry)`);
    assert.ok(sw.includes(`"${url}"`), `${url} is in CORE_ASSETS`);
  }
});

function runBoot({ pathname, profileRow, planRow, now = Date.UTC(2026, 8, 26, 12) }) {
  const links = [];
  const calls = [];
  const storage = {
    cairn_token: "",
    "cairn.swr.v1.profile": profileRow == null ? null : JSON.stringify(profileRow),
    "cairn.swr.v1.plan": planRow == null ? null : JSON.stringify(planRow),
  };
  const context = {
    location: { pathname },
    localStorage: { getItem: (key) => storage[key] ?? null },
    Intl: { DateTimeFormat: () => ({ resolvedOptions: () => ({ timeZone: "UTC" }) }) },
    document: {
      createElement: () => ({}),
      head: { appendChild: (node) => links.push(node) },
    },
    fetch: (url) => {
      calls.push(url);
      return Promise.resolve({ status: 200 });
    },
    Date: class extends Date {
      constructor(...args) {
        if (args.length) super(...args);
        else super(now);
      }
      static now() {
        return now;
      }
    },
  };
  context.window = context;
  vm.runInNewContext(earlyFetchScript(html), context);
  return { links, calls, early: context.__cairnEarly };
}

test("a Health deep link preloads Train then Me/Health and starts the overview's reads", () => {
  const { links, calls, early } = runBoot({ pathname: "/app/you/markers" });
  assert.deepEqual(
    links.map((l) => [l.rel, l.as, l.fetchPriority, l.href]),
    [
      ["preload", "script", "low", "/js/bundle-08-train.js"],
      ["preload", "script", "low", "/js/bundle-05-me-health.js"],
    ]
  );
  const reads = [...SHELL_EARLY_READS, ...VIEW_EARLY_READS.stand, "/profile"];
  const share = runBoot({ pathname: "/app/you/share" });
  assert.deepEqual(share.calls, [
    ...[...SHELL_EARLY_READS, ...VIEW_EARLY_READS.stand, "/symptom-links", "/health-report.json", "/profile"].map(
      (p) => `/api${p}`
    ),
  ]);
  assert.deepEqual(
    calls,
    reads.map((p) => `/api${p}`)
  );
  assert.deepEqual(Object.keys(early), reads);
});

test("Train, Horizon, Ask and Settings links preload their closure and start only the shell's reads", () => {
  const cases = {
    "/APP/Train": ["/js/bundle-08-train.js"],
    "/app/horizon": ["/js/bundle-08-train.js", "/js/bundle-09-horizon.js"],
    "/app/horizon/race": ["/js/bundle-08-train.js", "/js/bundle-09-horizon.js"],
    "/app/ask": ["/js/bundle-10-ask.js"],
    "/app/ask/changes": ["/js/bundle-10-ask.js"],
    "/app/you/settings/agents": ["/js/bundle-11-settings.js"],
    "/app/you/profile": ["/js/bundle-08-train.js", "/js/bundle-05-me-health.js"],
  };
  for (const [pathname, hrefs] of Object.entries(cases)) {
    const { links, calls } = runBoot({ pathname });
    assert.deepEqual(
      links.map((l) => l.href),
      hrefs,
      pathname
    );
    assert.deepEqual(
      calls,
      [...SHELL_EARLY_READS, "/profile"].map((p) => `/api${p}`),
      pathname
    );
  }
  const program = runBoot({ pathname: "/app/train/program" });
  assert.deepEqual(
    program.links.map((l) => l.href),
    ["/js/bundle-08-train.js"]
  );
  assert.deepEqual(
    program.calls,
    [...SHELL_EARLY_READS, "/coaching-focus", "/program-state", "/profile"].map((p) => `/api${p}`)
  );
  const plan = runBoot({ pathname: "/app/train/plan" });
  assert.deepEqual(
    plan.links.map((l) => l.href),
    ["/js/bundle-08-train.js"]
  );
  assert.deepEqual(
    plan.calls,
    [...SHELL_EARLY_READS, "/plan/week", "/plan/recovery-status", "/plan/upcoming", "/plan", "/profile"].map(
      (p) => `/api${p}`
    )
  );
});

test("/plan is asked early unless cachedApi would answer it from a row under 3 s old", () => {
  const now = Date.UTC(2026, 8, 26, 12);
  const young = runBoot({ pathname: "/app/train/plan", now, planRow: { data: [], ts: now - 2000 } });
  assert.ok(!young.calls.includes("/api/plan"));
  const older = runBoot({ pathname: "/app/train/plan", now, planRow: { data: [], ts: now - 3000 } });
  assert.ok(older.calls.includes("/api/plan"));
  const shapeless = runBoot({ pathname: "/app/train/plan", now, planRow: { ts: now } });
  assert.ok(shapeless.calls.includes("/api/plan"), "a row without data never peeks");
});

test("/profile is asked early only when primeDiscipline will ask for it", () => {
  const now = Date.UTC(2026, 8, 26, 12);
  const fresh = runBoot({
    pathname: "/app/train",
    now,
    profileRow: { data: { primary_discipline: "hybrid" }, ts: now - 60_000 },
  });
  assert.ok(!fresh.calls.includes("/api/profile"), "a remembered profile primes synchronously");
  const swept = runBoot({ pathname: "/app/train", now, profileRow: { data: { a: 1 }, ts: now - 25 * 3600_000 } });
  assert.ok(swept.calls.includes("/api/profile"), "a row the boot sweep evicts is asked for");
  const empty = runBoot({ pathname: "/app/train", now, profileRow: { data: null, ts: now } });
  assert.ok(empty.calls.includes("/api/profile"), "an empty row does not prime");
});

test("eager destinations, Today and nonsense paths preload nothing", () => {
  for (const pathname of [
    "/app/today/session",
    "/app/today/fuel",
    "/app/you",
    "/app/you/stone",
    "/constructor",
    "/app/constructor/x",
    "/x/y/z",
  ]) {
    const { links, calls } = runBoot({ pathname });
    assert.deepEqual(links, [], pathname);
    assert.deepEqual(calls, [], pathname);
  }
  const today = runBoot({ pathname: "/app/today" });
  assert.deepEqual(today.links, []);
  assert.equal(today.calls.length, 3, "Today keeps its own three reads");
});

test("a shell without a document still starts the reads", () => {
  const context = {
    location: { pathname: "/app/ask" },
    localStorage: { getItem: () => null },
    Intl: { DateTimeFormat: () => ({ resolvedOptions: () => ({ timeZone: "UTC" }) }) },
    fetch: () => Promise.resolve({ status: 200 }),
  };
  context.window = context;
  vm.runInNewContext(earlyFetchScript(html), context);
  assert.deepEqual(Object.keys(context.__cairnEarly), [...SHELL_EARLY_READS, "/profile"]);
});

// Each early read must be asked for, through api(), on every open of its route —
// otherwise its response is never taken and it costs a request.
test("the early reads are the ones the boot and the Health overview always ask for", () => {
  const stand = read("src/client/stand-screen.ts");
  const body = /async function fetchStandData\(\)[\s\S]*?\]\);/.exec(stand)?.[0] || "";
  assert.deepEqual(
    [...body.matchAll(/api\("([^"]+)"\)/g)].map((m) => m[1]),
    VIEW_EARLY_READS.stand
  );
  // Every Stand entry (cold or snapshot-warm, any section) runs fetchStandData.
  const render = /async function renderStand\(\)[\s\S]*?\n {2}\}\n/.exec(stand)?.[0] || "";
  assert.match(render, /void revalidateStand\(\)[\s\S]*void loadStandData\(\)/);

  // The plan editor asks its three head reads on every first paint (a repaint reuses them).
  const head = read("src/client/plan-head-client.ts");
  const heads = /function planHeadReads\(\)[\s\S]*?\n\}/.exec(head)?.[0] || "";
  assert.deepEqual(
    [...heads.matchAll(/planHeadRead\("([^"]+)"\)/g)].map((m) => m[1]),
    VIEW_EARLY_READS["plan:edit"].slice(0, 3)
  );
  assert.deepEqual(VIEW_EARLY_READS["plan:edit"][3], ["/plan", "plan", 3000]);
  assert.match(
    read("src/client/plan-editor-controller.ts"),
    /const revalidate = cachedApi\("\/plan", \{\s*key: "plan",\s*onUpgrade/
  );
  assert.match(
    read("src/client/swr-cache.ts"),
    /const \{ key, freshFor = 60000, serveFreshFor = 3000, onUpgrade, project \} = options;/
  );
  assert.match(
    read("src/client/plan-editor-controller.ts"),
    /const heads: PlanHeadReads = reuseHeads \?\? CairnPlanHead\.headReads\(\);/
  );
  assert.match(
    read("src/client/plan-editor-controller.ts"),
    /async function renderPlanEditor\(\): Promise<void> \{\s*return paintPlanEditor\(\);/
  );
  assert.deepEqual(Object.keys(VIEW_EARLY_READS).sort(), ["plan:edit", "progress:program", "stand", "stand:share"]);

  // Train › Program: the conductor through api(), program-state through paintSWR.
  assert.deepEqual(VIEW_EARLY_READS["progress:program"], [
    "/coaching-focus",
    ["/program-state", "progress:program", 3000],
  ]);
  const program =
    /async function renderProgressProgram\([\s\S]*?\n\}\n/.exec(
      read("src/client/progress-program-controller.ts")
    )?.[0] || "";
  assert.match(program, /deps\s*\.api\("\/coaching-focus"\)/);
  assert.match(
    program,
    /return deps\.paintSWR\(\{\s*key: "progress:program",\s*path: "\/program-state",\s*peek,\s*token,\s*tab: "progress",\s*render/
  );
  assert.match(read("src/client/swr-cache.ts"), /return cachedApi\(path, \{\s*key,\s*freshFor,\s*serveFreshFor,/);

  // Health › Doctor packet: showShare always loads the symptom links and mounts the
  // packet builder, whose first load asks cachedApi on a memory-only key.
  assert.deepEqual(VIEW_EARLY_READS["stand:share"], ["/symptom-links", ["/health-report.json", "health:packet", 3000]]);
  const share = /function showShare\(\): void \{[\s\S]*?\n {2}\}\n/.exec(stand)?.[0] || "";
  assert.match(share, /CairnRecordsSlot\.mount\("packet"/);
  assert.match(share, /void CairnHealthReadController\.loadSymptomLinks\(/);
  assert.match(
    read("src/client/health-read-controller.ts"),
    /async function loadSymptomLinks[\s\S]*?deps\.api\("\/symptom-links"\)/
  );
  const packet = read("src/client/packet-builder-controller.ts");
  assert.match(packet, /const KEY = "health:packet";\s*const PATH = "\/health-report\.json";/);
  assert.match(packet, /request = deps\.cachedApi\(PATH, \{ key: KEY \}\);/);
  assert.match(
    read("src/client/health-share-controller.ts"),
    /CairnRecordsSlot\.register\("packet", mountHealthPacket\)/
  );
  assert.match(read("src/client/swr-cache.ts"), /function _swrMemOnly[\s\S]*?\^\(markers:\|recovery:\|health:/);

  const startup = read("src/client/app/startup.ts");
  for (const call of ["primeDiscipline();", "maybeOnboard();", "primeArtManifest();", "jobReconnect();"]) {
    assert.ok(startup.includes(call), `startAppShell calls ${call}`);
  }
  assert.match(
    read("src/client/app/onboarding.ts"),
    /async function maybeOnboard\(\)[\s\S]*?await api\("\/settings"\)/
  );
  assert.match(
    read("src/client/art-controller.ts"),
    /async function primeArtManifest\(\)[\s\S]*?await api\("\/art\/state"\)/
  );
  assert.match(
    read("src/client/agent-job-client.ts"),
    /async function jobReconnect\(\)[\s\S]*?await api\("\/agent-jobs"\)/
  );
  assert.deepEqual(SHELL_EARLY_READS, ["/settings", "/art/state", "/agent-jobs"]);

  // /profile: primeDiscipline asks only without a remembered "profile" row, and the
  // boot sweep drops rows older than a day — the inline script mirrors both.
  assert.match(
    read("src/client/app/discipline-primer.ts"),
    /peekCached<[^>]*>\("profile"\)[\s\S]*if \(warm && warm\.data\)[\s\S]*api\("\/profile"\)/
  );
  const swr = read("src/client/swr-cache.ts");
  assert.match(swr, /const SWR_NS = "cairn\.swr\.v1\.";/);
  assert.match(swr, /function swrSweep\(\): void \{\s*const MAX_AGE = 24 \* 60 \* 60 \* 1000;/);
  assert.ok(earlyFetchScript(html).includes('localStorage.getItem("cairn.swr.v1.profile")'));
  assert.ok(earlyFetchScript(html).includes("<=864e5"));
});

test("api() hands each early response over once, keyed by the path it is asked with", () => {
  const context = { globalThis: null, window: {} };
  context.globalThis = context;
  vm.runInNewContext(read("public/js/today-prefetch.js"), context);
  const res = Promise.resolve({ status: 200 });
  context.__cairnEarly = { "/markers/priority": { at: Date.now(), res } };
  assert.ok(context.CairnTodayPrefetch.takeEarly("/markers/priority"));
  assert.equal(context.CairnTodayPrefetch.takeEarly("/markers/priority"), undefined, "never twice");
});

test("a route's bundle string is one digit per index, and an 11th bundle url fails the build", () => {
  assert.equal(bundleDigits([0, 3, 9]), "039");
  assert.throws(() => bundleDigits([1, 10]), /not one digit/);
  assert.ok(table.b.length <= 10, "today's table fits the encoding");
});
