#!/usr/bin/env node
// Concatenate the stylesheet partials under src/styles/ into public/styles.css.
//
// The app ships ONE stylesheet (index.html links it, the service worker precaches
// it, the build precompresses it), but it is authored as per-surface partials so a
// screen stream edits only the files it owns (docs/DESIGN.md "Stylesheet ownership").
// The ORDER below is the cascade: a later partial wins a same-specificity tie, so a
// partial never moves without reading what it would now override. Every .css file
// under src/styles/ must appear here exactly once; an unlisted or missing partial
// fails the build rather than silently dropping rules.
//
// public/styles.css stays committed (the Docker runtime stage and the test suite
// read it straight from the checkout), so `--check` (run by `npm run verify`) fails
// when the committed file drifts from its partials.
//
// Usage: node scripts/build-styles.mjs [--check]
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const currentFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(currentFile), "..");

export const STYLES_DIR = "src/styles";
export const STYLES_OUTPUT = "public/styles.css";

/** The cascade order. Foundation first, then the surfaces in their historical order. */
export const STYLE_PARTIALS = [
  "foundation/tokens",
  "foundation/fonts",
  "foundation/base",
  "foundation/motion",
  "foundation/primitives",
  "foundation/stones",
  "foundation/cards",
  "foundation/components",
  "today/header",
  "session/exercise",
  "foundation/segments",
  "train/plan-editor",
  "train/progress",
  "fuel/meal-plans",
  "ask/chat",
  "settings/settings",
  "you/records",
  "shell/overlays",
  "shell/tabbar",
  "shell/responsive-nav",
  "shell/detail",
  "fuel/planner",
  "today/date",
  "fuel/meal-sheet",
  "train/progress-editorial",
  "today/garmin",
  "today/brief",
  "foundation/loading",
  "ask/capture",
  "settings/groups",
  "foundation/reduced-motion",
  "health/health",
  "health/stand",
  "you/profile",
  "shell/responsive",
  "train/endurance",
  "foundation/a11y",
  "train/program",
  "train/strength",
  "session/destination",
  "train/overview",
  "ask/changes",
  "fuel/meal-card",
  "fuel/today",
  "health/records",
  "health/packet",
  "horizon/race",
  "today/pebbles",
  "you/cairn",
  "shell/identity",
  "shell/nav",
  "ask/ask",
  "horizon/horizon",
];

const BANNER =
  "/* GENERATED by scripts/build-styles.mjs from src/styles/**. Edit the partials, never this file.\n" +
  "   Cascade order and ownership: docs/DESIGN.md \"Stylesheet ownership\". */\n";

function listPartials(dir = STYLES_DIR) {
  const out = [];
  const abs = path.join(root, dir);
  if (!existsSync(abs)) return out;
  for (const entry of readdirSync(abs, { withFileTypes: true })) {
    const rel = `${dir}/${entry.name}`;
    if (entry.isDirectory()) out.push(...listPartials(rel));
    else if (entry.name.endsWith(".css")) out.push(rel.slice(STYLES_DIR.length + 1, -".css".length));
  }
  return out;
}

/** The stylesheet the partials produce, or throws naming the partials out of step. */
export function renderStyles() {
  const onDisk = new Set(listPartials());
  const listed = new Set(STYLE_PARTIALS);
  const problems = [];
  if (listed.size !== STYLE_PARTIALS.length) problems.push("a partial is listed twice in STYLE_PARTIALS");
  for (const name of STYLE_PARTIALS) if (!onDisk.has(name)) problems.push(`listed but missing: ${STYLES_DIR}/${name}.css`);
  for (const name of onDisk) if (!listed.has(name)) problems.push(`not in STYLE_PARTIALS: ${STYLES_DIR}/${name}.css`);
  if (problems.length) throw new Error(`stylesheet partials out of step:\n  ${problems.join("\n  ")}`);
  let css = BANNER;
  for (const name of STYLE_PARTIALS) {
    const chunk = readFileSync(path.join(root, STYLES_DIR, `${name}.css`), "utf8");
    css += chunk.endsWith("\n") ? chunk : `${chunk}\n`;
  }
  return css;
}

export function buildStyles() {
  const css = renderStyles();
  const target = path.join(root, STYLES_OUTPUT);
  const before = existsSync(target) ? readFileSync(target, "utf8") : null;
  if (before !== css) writeFileSync(target, css);
  console.log(`✓ built ${STYLES_OUTPUT} from ${STYLE_PARTIALS.length} partials (${(css.length / 1024).toFixed(0)} KB)`);
}

export function checkStyles() {
  const css = renderStyles();
  const target = path.join(root, STYLES_OUTPUT);
  const committed = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (committed !== css) {
    console.error(`✗ ${STYLES_OUTPUT} is out of date with ${STYLES_DIR}/. Run: node scripts/build-styles.mjs`);
    process.exit(1);
  }
  console.log(`✓ ${STYLES_OUTPUT} matches its ${STYLE_PARTIALS.length} partials`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === currentFile) {
  try {
    if (process.argv.includes("--check")) checkStyles();
    else buildStyles();
  } catch (error) {
    console.error(`✗ ${error instanceof Error ? error.message : String(error)}`);
    process.exit(1);
  }
}
